# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/Aman
Accept: application/json

###

GET http://127.0.0.1:8000/profiling_summary/
Accept: application/json

###

GET http://127.0.0.1:8000/profiling_summary/3
Accept: application/json
